# Generated by Django 4.1.7 on 2023-10-30 01:39

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
    ]
